apiVersion: v1
kind: Service
metadata:
  name: backup-restore-metrics
  namespace: {{ .Release.Namespace }}
  labels: {{- include "backup-restore.labels" . | nindent 4 }}
spec:
  selector:
    app.kubernetes.io/name: {{ include "backup-restore.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
  - {name: metrics, port: 8080, targetPort: metrics}
