{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "backup-restore.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "backup-restore.labels" . | nindent 4 }}
{{- end }}
