{{- if .Values.metrics.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "backup-restore.name" . }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "backup-restore.name" . }}
  endpoints:
  - {port: metrics, interval: {{ .Values.metrics.serviceMonitor.interval }}}
{{- end }}
