// Copyright 2026.
// SPDX-License-Identifier: Apache-2.0

// Package v1alpha1 contains cluster-scoped backup and restore APIs.
//
// +kubebuilder:webhook:path=/mutate-protection-platform-io-v1alpha1-backuprepository,mutating=true,failurePolicy=fail,sideEffects=None,groups=protection.platform.io,resources=backuprepositories,verbs=create;update,versions=v1alpha1,name=mbackuprepository.protection.platform.io,admissionReviewVersions=v1
// +kubebuilder:webhook:path=/validate-protection-platform-io-v1alpha1-backuprepository,mutating=false,failurePolicy=fail,sideEffects=None,groups=protection.platform.io,resources=backuprepositories,verbs=create;update,versions=v1alpha1,name=vbackuprepository.protection.platform.io,admissionReviewVersions=v1
// +kubebuilder:webhook:path=/mutate-protection-platform-io-v1alpha1-backupscope,mutating=true,failurePolicy=fail,sideEffects=None,groups=protection.platform.io,resources=backupscopes,verbs=create;update,versions=v1alpha1,name=mbackupscope.protection.platform.io,admissionReviewVersions=v1
// +kubebuilder:webhook:path=/validate-protection-platform-io-v1alpha1-backupscope,mutating=false,failurePolicy=fail,sideEffects=None,groups=protection.platform.io,resources=backupscopes,verbs=create;update,versions=v1alpha1,name=vbackupscope.protection.platform.io,admissionReviewVersions=v1
// +kubebuilder:webhook:path=/mutate-protection-platform-io-v1alpha1-backuppolicy,mutating=true,failurePolicy=fail,sideEffects=None,groups=protection.platform.io,resources=backuppolicies,verbs=create;update,versions=v1alpha1,name=mbackuppolicy.protection.platform.io,admissionReviewVersions=v1
// +kubebuilder:webhook:path=/validate-protection-platform-io-v1alpha1-backuppolicy,mutating=false,failurePolicy=fail,sideEffects=None,groups=protection.platform.io,resources=backuppolicies,verbs=create;update,versions=v1alpha1,name=vbackuppolicy.protection.platform.io,admissionReviewVersions=v1
// +kubebuilder:webhook:path=/mutate-protection-platform-io-v1alpha1-backuptask,mutating=true,failurePolicy=fail,sideEffects=None,groups=protection.platform.io,resources=backuptasks,verbs=create;update,versions=v1alpha1,name=mbackuptask.protection.platform.io,admissionReviewVersions=v1
// +kubebuilder:webhook:path=/validate-protection-platform-io-v1alpha1-backuptask,mutating=false,failurePolicy=fail,sideEffects=None,groups=protection.platform.io,resources=backuptasks,verbs=create;update,versions=v1alpha1,name=vbackuptask.protection.platform.io,admissionReviewVersions=v1
// +kubebuilder:webhook:path=/validate-protection-platform-io-v1alpha1-backuprecord,mutating=false,failurePolicy=fail,sideEffects=None,groups=protection.platform.io,resources=backuprecords,verbs=create;update;delete,versions=v1alpha1,name=vbackuprecord.protection.platform.io,admissionReviewVersions=v1
// +kubebuilder:webhook:path=/mutate-protection-platform-io-v1alpha1-restoretask,mutating=true,failurePolicy=fail,sideEffects=None,groups=protection.platform.io,resources=restoretasks,verbs=create;update,versions=v1alpha1,name=mrestoretask.protection.platform.io,admissionReviewVersions=v1
// +kubebuilder:webhook:path=/validate-protection-platform-io-v1alpha1-restoretask,mutating=false,failurePolicy=fail,sideEffects=None,groups=protection.platform.io,resources=restoretasks,verbs=create;update,versions=v1alpha1,name=vrestoretask.protection.platform.io,admissionReviewVersions=v1
// +kubebuilder:webhook:path=/mutate-protection-platform-io-v1alpha1-backuppluginconfig,mutating=true,failurePolicy=fail,sideEffects=None,groups=protection.platform.io,resources=backuppluginconfigs,verbs=create;update,versions=v1alpha1,name=mbackuppluginconfig.protection.platform.io,admissionReviewVersions=v1
// +kubebuilder:webhook:path=/validate-protection-platform-io-v1alpha1-backuppluginconfig,mutating=false,failurePolicy=fail,sideEffects=None,groups=protection.platform.io,resources=backuppluginconfigs,verbs=create;update,versions=v1alpha1,name=vbackuppluginconfig.protection.platform.io,admissionReviewVersions=v1
package v1alpha1
