//go:build !ignore_autogenerated

// Copyright 2026.
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BackupInventory) DeepCopyInto(out *BackupInventory) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BackupInventory.
func (in *BackupInventory) DeepCopy() *BackupInventory {
	if in == nil {
		return nil
	}
	out := new(BackupInventory)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BackupPluginConfig) DeepCopyInto(out *BackupPluginConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BackupPluginConfig.
func (in *BackupPluginConfig) DeepCopy() *BackupPluginConfig {
	if in == nil {
		return nil
	}
	out := new(BackupPluginConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BackupPluginConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BackupPluginConfigList) DeepCopyInto(out *BackupPluginConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]BackupPluginConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BackupPluginConfigList.
func (in *BackupPluginConfigList) DeepCopy() *BackupPluginConfigList {
	if in == nil {
		return nil
	}
	out := new(BackupPluginConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BackupPluginConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BackupPluginConfigSpec) DeepCopyInto(out *BackupPluginConfigSpec) {
	*out = *in
	out.DefaultBackupTimeout = in.DefaultBackupTimeout
	out.DefaultRestoreTimeout = in.DefaultRestoreTimeout
	out.DefaultSnapshotTimeout = in.DefaultSnapshotTimeout
	out.Concurrency = in.Concurrency
	out.KubernetesClient = in.KubernetesClient
	in.Security.DeepCopyInto(&out.Security)
	out.GarbageCollection = in.GarbageCollection
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BackupPluginConfigSpec.
func (in *BackupPluginConfigSpec) DeepCopy() *BackupPluginConfigSpec {
	if in == nil {
		return nil
	}
	out := new(BackupPluginConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BackupPluginConfigStatus) DeepCopyInto(out *BackupPluginConfigStatus) {
	*out = *in
	in.CommonStatus.DeepCopyInto(&out.CommonStatus)
	if in.LastAppliedAt != nil {
		in, out := &in.LastAppliedAt, &out.LastAppliedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BackupPluginConfigStatus.
func (in *BackupPluginConfigStatus) DeepCopy() *BackupPluginConfigStatus {
	if in == nil {
		return nil
	}
	out := new(BackupPluginConfigStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BackupPolicy) DeepCopyInto(out *BackupPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BackupPolicy.
func (in *BackupPolicy) DeepCopy() *BackupPolicy {
	if in == nil {
		return nil
	}
	out := new(BackupPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BackupPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BackupPolicyList) DeepCopyInto(out *BackupPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]BackupPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BackupPolicyList.
func (in *BackupPolicyList) DeepCopy() *BackupPolicyList {
	if in == nil {
		return nil
	}
	out := new(BackupPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BackupPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BackupPolicySpec) DeepCopyInto(out *BackupPolicySpec) {
	*out = *in
	out.ResourceIdentity = in.ResourceIdentity
	in.Selection.DeepCopyInto(&out.Selection)
	out.RepositoryRef = in.RepositoryRef
	out.Schedule = in.Schedule
	out.StartingDeadline = in.StartingDeadline
	out.Retention = in.Retention
	in.RetryPolicy.DeepCopyInto(&out.RetryPolicy)
	out.Timeout = in.Timeout
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BackupPolicySpec.
func (in *BackupPolicySpec) DeepCopy() *BackupPolicySpec {
	if in == nil {
		return nil
	}
	out := new(BackupPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BackupPolicyStatus) DeepCopyInto(out *BackupPolicyStatus) {
	*out = *in
	in.CommonStatus.DeepCopyInto(&out.CommonStatus)
	in.SelectionPreview.DeepCopyInto(&out.SelectionPreview)
	if in.LastScheduleTime != nil {
		in, out := &in.LastScheduleTime, &out.LastScheduleTime
		*out = (*in).DeepCopy()
	}
	if in.LastSuccessfulTime != nil {
		in, out := &in.LastSuccessfulTime, &out.LastSuccessfulTime
		*out = (*in).DeepCopy()
	}
	if in.LastEvaluatedScheduleTime != nil {
		in, out := &in.LastEvaluatedScheduleTime, &out.LastEvaluatedScheduleTime
		*out = (*in).DeepCopy()
	}
	if in.NextScheduleTime != nil {
		in, out := &in.NextScheduleTime, &out.NextScheduleTime
		*out = (*in).DeepCopy()
	}
	if in.ActiveTasks != nil {
		in, out := &in.ActiveTasks, &out.ActiveTasks
		*out = make([]ObjectReference, len(*in))
		copy(*out, *in)
	}
	if in.SkippedRuns != nil {
		in, out := &in.SkippedRuns, &out.SkippedRuns
		*out = make([]SkippedRun, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BackupPolicyStatus.
func (in *BackupPolicyStatus) DeepCopy() *BackupPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(BackupPolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BackupRecord) DeepCopyInto(out *BackupRecord) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BackupRecord.
func (in *BackupRecord) DeepCopy() *BackupRecord {
	if in == nil {
		return nil
	}
	out := new(BackupRecord)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BackupRecord) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BackupRecordList) DeepCopyInto(out *BackupRecordList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]BackupRecord, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BackupRecordList.
func (in *BackupRecordList) DeepCopy() *BackupRecordList {
	if in == nil {
		return nil
	}
	out := new(BackupRecordList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BackupRecordList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BackupRecordSpec) DeepCopyInto(out *BackupRecordSpec) {
	*out = *in
	out.ResourceIdentity = in.ResourceIdentity
	out.SourceTaskRef = in.SourceTaskRef
	out.PolicyRef = in.PolicyRef
	out.RepositoryRef = in.RepositoryRef
	in.Source.DeepCopyInto(&out.Source)
	in.Encryption.DeepCopyInto(&out.Encryption)
	out.Inventory = in.Inventory
	if in.Snapshots != nil {
		in, out := &in.Snapshots, &out.Snapshots
		*out = make([]SnapshotResult, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ExpiresAt != nil {
		in, out := &in.ExpiresAt, &out.ExpiresAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BackupRecordSpec.
func (in *BackupRecordSpec) DeepCopy() *BackupRecordSpec {
	if in == nil {
		return nil
	}
	out := new(BackupRecordSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BackupRecordStatus) DeepCopyInto(out *BackupRecordStatus) {
	*out = *in
	in.CommonStatus.DeepCopyInto(&out.CommonStatus)
	if in.LastVerifiedAt != nil {
		in, out := &in.LastVerifiedAt, &out.LastVerifiedAt
		*out = (*in).DeepCopy()
	}
	if in.MissingSnapshots != nil {
		in, out := &in.MissingSnapshots, &out.MissingSnapshots
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.LastRestoreTime != nil {
		in, out := &in.LastRestoreTime, &out.LastRestoreTime
		*out = (*in).DeepCopy()
	}
	in.Deletion.DeepCopyInto(&out.Deletion)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BackupRecordStatus.
func (in *BackupRecordStatus) DeepCopy() *BackupRecordStatus {
	if in == nil {
		return nil
	}
	out := new(BackupRecordStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BackupRepository) DeepCopyInto(out *BackupRepository) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BackupRepository.
func (in *BackupRepository) DeepCopy() *BackupRepository {
	if in == nil {
		return nil
	}
	out := new(BackupRepository)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BackupRepository) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BackupRepositoryList) DeepCopyInto(out *BackupRepositoryList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]BackupRepository, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BackupRepositoryList.
func (in *BackupRepositoryList) DeepCopy() *BackupRepositoryList {
	if in == nil {
		return nil
	}
	out := new(BackupRepositoryList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BackupRepositoryList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BackupRepositorySpec) DeepCopyInto(out *BackupRepositorySpec) {
	*out = *in
	out.ResourceIdentity = in.ResourceIdentity
	if in.Local != nil {
		in, out := &in.Local, &out.Local
		*out = new(LocalRepositorySpec)
		(*in).DeepCopyInto(*out)
	}
	if in.SFTP != nil {
		in, out := &in.SFTP, &out.SFTP
		*out = new(SFTPRepositorySpec)
		(*in).DeepCopyInto(*out)
	}
	out.Compression = in.Compression
	in.Encryption.DeepCopyInto(&out.Encryption)
	out.HealthCheckInterval = in.HealthCheckInterval
	out.Timeout = in.Timeout
	if in.MinimumFreeBytes != nil {
		in, out := &in.MinimumFreeBytes, &out.MinimumFreeBytes
		x := (*in).DeepCopy()
		*out = &x
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BackupRepositorySpec.
func (in *BackupRepositorySpec) DeepCopy() *BackupRepositorySpec {
	if in == nil {
		return nil
	}
	out := new(BackupRepositorySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BackupRepositoryStatus) DeepCopyInto(out *BackupRepositoryStatus) {
	*out = *in
	in.CommonStatus.DeepCopyInto(&out.CommonStatus)
	out.Capabilities = in.Capabilities
	if in.LastCheckTime != nil {
		in, out := &in.LastCheckTime, &out.LastCheckTime
		*out = (*in).DeepCopy()
	}
	if in.LastSuccessfulCheckTime != nil {
		in, out := &in.LastSuccessfulCheckTime, &out.LastSuccessfulCheckTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BackupRepositoryStatus.
func (in *BackupRepositoryStatus) DeepCopy() *BackupRepositoryStatus {
	if in == nil {
		return nil
	}
	out := new(BackupRepositoryStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BackupScheduleSpec) DeepCopyInto(out *BackupScheduleSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BackupScheduleSpec.
func (in *BackupScheduleSpec) DeepCopy() *BackupScheduleSpec {
	if in == nil {
		return nil
	}
	out := new(BackupScheduleSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BackupSelectionSpec) DeepCopyInto(out *BackupSelectionSpec) {
	*out = *in
	if in.IncludeNamespaces != nil {
		in, out := &in.IncludeNamespaces, &out.IncludeNamespaces
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ExcludeNamespaces != nil {
		in, out := &in.ExcludeNamespaces, &out.ExcludeNamespaces
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	in.Resources.DeepCopyInto(&out.Resources)
	if in.LabelSelector != nil {
		in, out := &in.LabelSelector, &out.LabelSelector
		*out = new(v1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
	in.PVC.DeepCopyInto(&out.PVC)
	in.Hooks.DeepCopyInto(&out.Hooks)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BackupSelectionSpec.
func (in *BackupSelectionSpec) DeepCopy() *BackupSelectionSpec {
	if in == nil {
		return nil
	}
	out := new(BackupSelectionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BackupSource) DeepCopyInto(out *BackupSource) {
	*out = *in
	if in.Namespaces != nil {
		in, out := &in.Namespaces, &out.Namespaces
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BackupSource.
func (in *BackupSource) DeepCopy() *BackupSource {
	if in == nil {
		return nil
	}
	out := new(BackupSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BackupTask) DeepCopyInto(out *BackupTask) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BackupTask.
func (in *BackupTask) DeepCopy() *BackupTask {
	if in == nil {
		return nil
	}
	out := new(BackupTask)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BackupTask) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BackupTaskList) DeepCopyInto(out *BackupTaskList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]BackupTask, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BackupTaskList.
func (in *BackupTaskList) DeepCopy() *BackupTaskList {
	if in == nil {
		return nil
	}
	out := new(BackupTaskList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BackupTaskList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BackupTaskSpec) DeepCopyInto(out *BackupTaskSpec) {
	*out = *in
	out.ResourceIdentity = in.ResourceIdentity
	out.PolicyRef = in.PolicyRef
	if in.ParentTaskRef != nil {
		in, out := &in.ParentTaskRef, &out.ParentTaskRef
		*out = new(ObjectReference)
		**out = **in
	}
	if in.ScheduledAt != nil {
		in, out := &in.ScheduledAt, &out.ScheduledAt
		*out = (*in).DeepCopy()
	}
	out.RepositoryRef = in.RepositoryRef
	if in.SelectionSnapshot != nil {
		in, out := &in.SelectionSnapshot, &out.SelectionSnapshot
		*out = new(BackupSelectionSpec)
		(*in).DeepCopyInto(*out)
	}
	out.Timeout = in.Timeout
	in.RetryPolicy.DeepCopyInto(&out.RetryPolicy)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BackupTaskSpec.
func (in *BackupTaskSpec) DeepCopy() *BackupTaskSpec {
	if in == nil {
		return nil
	}
	out := new(BackupTaskSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BackupTaskStatus) DeepCopyInto(out *BackupTaskStatus) {
	*out = *in
	in.CommonStatus.DeepCopyInto(&out.CommonStatus)
	out.Progress = in.Progress
	if in.LastHeartbeatTime != nil {
		in, out := &in.LastHeartbeatTime, &out.LastHeartbeatTime
		*out = (*in).DeepCopy()
	}
	if in.Checkpoints != nil {
		in, out := &in.Checkpoints, &out.Checkpoints
		*out = make([]TaskCheckpoint, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Errors != nil {
		in, out := &in.Errors, &out.Errors
		*out = make([]ErrorDetail, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Snapshots != nil {
		in, out := &in.Snapshots, &out.Snapshots
		*out = make([]SnapshotResult, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.RecordRef != nil {
		in, out := &in.RecordRef, &out.RecordRef
		*out = new(ObjectReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BackupTaskStatus.
func (in *BackupTaskStatus) DeepCopy() *BackupTaskStatus {
	if in == nil {
		return nil
	}
	out := new(BackupTaskStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CommonStatus) DeepCopyInto(out *CommonStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.CreatedAt != nil {
		in, out := &in.CreatedAt, &out.CreatedAt
		*out = (*in).DeepCopy()
	}
	if in.StartedAt != nil {
		in, out := &in.StartedAt, &out.StartedAt
		*out = (*in).DeepCopy()
	}
	if in.CompletedAt != nil {
		in, out := &in.CompletedAt, &out.CompletedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CommonStatus.
func (in *CommonStatus) DeepCopy() *CommonStatus {
	if in == nil {
		return nil
	}
	out := new(CommonStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConcurrencyConfig) DeepCopyInto(out *ConcurrencyConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConcurrencyConfig.
func (in *ConcurrencyConfig) DeepCopy() *ConcurrencyConfig {
	if in == nil {
		return nil
	}
	out := new(ConcurrencyConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ErrorDetail) DeepCopyInto(out *ErrorDetail) {
	*out = *in
	if in.ObjectRef != nil {
		in, out := &in.ObjectRef, &out.ObjectRef
		*out = new(ResourceObjectRef)
		**out = **in
	}
	in.At.DeepCopyInto(&out.At)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ErrorDetail.
func (in *ErrorDetail) DeepCopy() *ErrorDetail {
	if in == nil {
		return nil
	}
	out := new(ErrorDetail)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExecutionProgress) DeepCopyInto(out *ExecutionProgress) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExecutionProgress.
func (in *ExecutionProgress) DeepCopy() *ExecutionProgress {
	if in == nil {
		return nil
	}
	out := new(ExecutionProgress)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GarbageCollectionConfig) DeepCopyInto(out *GarbageCollectionConfig) {
	*out = *in
	out.Interval = in.Interval
	out.StagingGracePeriod = in.StagingGracePeriod
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GarbageCollectionConfig.
func (in *GarbageCollectionConfig) DeepCopy() *GarbageCollectionConfig {
	if in == nil {
		return nil
	}
	out := new(GarbageCollectionConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HookSpec) DeepCopyInto(out *HookSpec) {
	*out = *in
	if in.Pre != nil {
		in, out := &in.Pre, &out.Pre
		*out = make([]ResourceHook, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Post != nil {
		in, out := &in.Post, &out.Post
		*out = make([]ResourceHook, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HookSpec.
func (in *HookSpec) DeepCopy() *HookSpec {
	if in == nil {
		return nil
	}
	out := new(HookSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubernetesClientConfig) DeepCopyInto(out *KubernetesClientConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubernetesClientConfig.
func (in *KubernetesClientConfig) DeepCopy() *KubernetesClientConfig {
	if in == nil {
		return nil
	}
	out := new(KubernetesClientConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LocalPVCReference) DeepCopyInto(out *LocalPVCReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LocalPVCReference.
func (in *LocalPVCReference) DeepCopy() *LocalPVCReference {
	if in == nil {
		return nil
	}
	out := new(LocalPVCReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LocalRepositorySpec) DeepCopyInto(out *LocalRepositorySpec) {
	*out = *in
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.PVC != nil {
		in, out := &in.PVC, &out.PVC
		*out = new(LocalPVCReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LocalRepositorySpec.
func (in *LocalRepositorySpec) DeepCopy() *LocalRepositorySpec {
	if in == nil {
		return nil
	}
	out := new(LocalRepositorySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ObjectReference) DeepCopyInto(out *ObjectReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ObjectReference.
func (in *ObjectReference) DeepCopy() *ObjectReference {
	if in == nil {
		return nil
	}
	out := new(ObjectReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PVCSelectionSpec) DeepCopyInto(out *PVCSelectionSpec) {
	*out = *in
	if in.Include != nil {
		in, out := &in.Include, &out.Include
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Exclude != nil {
		in, out := &in.Exclude, &out.Exclude
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.LabelSelector != nil {
		in, out := &in.LabelSelector, &out.LabelSelector
		*out = new(v1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.SnapshotClassMapping != nil {
		in, out := &in.SnapshotClassMapping, &out.SnapshotClassMapping
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	out.SnapshotTimeout = in.SnapshotTimeout
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PVCSelectionSpec.
func (in *PVCSelectionSpec) DeepCopy() *PVCSelectionSpec {
	if in == nil {
		return nil
	}
	out := new(PVCSelectionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RecordDeletionStatus) DeepCopyInto(out *RecordDeletionStatus) {
	*out = *in
	if in.StartedAt != nil {
		in, out := &in.StartedAt, &out.StartedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RecordDeletionStatus.
func (in *RecordDeletionStatus) DeepCopy() *RecordDeletionStatus {
	if in == nil {
		return nil
	}
	out := new(RecordDeletionStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RecordEncryptionSpec) DeepCopyInto(out *RecordEncryptionSpec) {
	*out = *in
	if in.KeyRef != nil {
		in, out := &in.KeyRef, &out.KeyRef
		*out = new(SecretKeyReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RecordEncryptionSpec.
func (in *RecordEncryptionSpec) DeepCopy() *RecordEncryptionSpec {
	if in == nil {
		return nil
	}
	out := new(RecordEncryptionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RepositoryCapabilities) DeepCopyInto(out *RepositoryCapabilities) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RepositoryCapabilities.
func (in *RepositoryCapabilities) DeepCopy() *RepositoryCapabilities {
	if in == nil {
		return nil
	}
	out := new(RepositoryCapabilities)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RepositoryCompressionSpec) DeepCopyInto(out *RepositoryCompressionSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RepositoryCompressionSpec.
func (in *RepositoryCompressionSpec) DeepCopy() *RepositoryCompressionSpec {
	if in == nil {
		return nil
	}
	out := new(RepositoryCompressionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RepositoryEncryptionSpec) DeepCopyInto(out *RepositoryEncryptionSpec) {
	*out = *in
	if in.KeyRef != nil {
		in, out := &in.KeyRef, &out.KeyRef
		*out = new(SecretKeyReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RepositoryEncryptionSpec.
func (in *RepositoryEncryptionSpec) DeepCopy() *RepositoryEncryptionSpec {
	if in == nil {
		return nil
	}
	out := new(RepositoryEncryptionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceHook) DeepCopyInto(out *ResourceHook) {
	*out = *in
	if in.PodSelector != nil {
		in, out := &in.PodSelector, &out.PodSelector
		*out = new(v1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.Command != nil {
		in, out := &in.Command, &out.Command
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	out.Timeout = in.Timeout
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceHook.
func (in *ResourceHook) DeepCopy() *ResourceHook {
	if in == nil {
		return nil
	}
	out := new(ResourceHook)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceIdentity) DeepCopyInto(out *ResourceIdentity) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceIdentity.
func (in *ResourceIdentity) DeepCopy() *ResourceIdentity {
	if in == nil {
		return nil
	}
	out := new(ResourceIdentity)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceObjectRef) DeepCopyInto(out *ResourceObjectRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceObjectRef.
func (in *ResourceObjectRef) DeepCopy() *ResourceObjectRef {
	if in == nil {
		return nil
	}
	out := new(ResourceObjectRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceSelection) DeepCopyInto(out *ResourceSelection) {
	*out = *in
	if in.Include != nil {
		in, out := &in.Include, &out.Include
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Exclude != nil {
		in, out := &in.Exclude, &out.Exclude
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.IncludeCluster != nil {
		in, out := &in.IncludeCluster, &out.IncludeCluster
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ExcludeCluster != nil {
		in, out := &in.ExcludeCluster, &out.ExcludeCluster
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceSelection.
func (in *ResourceSelection) DeepCopy() *ResourceSelection {
	if in == nil {
		return nil
	}
	out := new(ResourceSelection)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RestoreConflictPolicy) DeepCopyInto(out *RestoreConflictPolicy) {
	*out = *in
	if in.PerResource != nil {
		in, out := &in.PerResource, &out.PerResource
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RestoreConflictPolicy.
func (in *RestoreConflictPolicy) DeepCopy() *RestoreConflictPolicy {
	if in == nil {
		return nil
	}
	out := new(RestoreConflictPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RestorePlanSummary) DeepCopyInto(out *RestorePlanSummary) {
	*out = *in
	if in.GeneratedAt != nil {
		in, out := &in.GeneratedAt, &out.GeneratedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RestorePlanSummary.
func (in *RestorePlanSummary) DeepCopy() *RestorePlanSummary {
	if in == nil {
		return nil
	}
	out := new(RestorePlanSummary)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RestoreProgress) DeepCopyInto(out *RestoreProgress) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RestoreProgress.
func (in *RestoreProgress) DeepCopy() *RestoreProgress {
	if in == nil {
		return nil
	}
	out := new(RestoreProgress)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RestoreResourceSelection) DeepCopyInto(out *RestoreResourceSelection) {
	*out = *in
	if in.Include != nil {
		in, out := &in.Include, &out.Include
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Exclude != nil {
		in, out := &in.Exclude, &out.Exclude
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RestoreResourceSelection.
func (in *RestoreResourceSelection) DeepCopy() *RestoreResourceSelection {
	if in == nil {
		return nil
	}
	out := new(RestoreResourceSelection)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RestoreTask) DeepCopyInto(out *RestoreTask) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RestoreTask.
func (in *RestoreTask) DeepCopy() *RestoreTask {
	if in == nil {
		return nil
	}
	out := new(RestoreTask)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RestoreTask) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RestoreTaskList) DeepCopyInto(out *RestoreTaskList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]RestoreTask, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RestoreTaskList.
func (in *RestoreTaskList) DeepCopy() *RestoreTaskList {
	if in == nil {
		return nil
	}
	out := new(RestoreTaskList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RestoreTaskList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RestoreTaskSpec) DeepCopyInto(out *RestoreTaskSpec) {
	*out = *in
	out.ResourceIdentity = in.ResourceIdentity
	if in.ParentTaskRef != nil {
		in, out := &in.ParentTaskRef, &out.ParentTaskRef
		*out = new(ObjectReference)
		**out = **in
	}
	out.BackupRecordRef = in.BackupRecordRef
	if in.NamespaceMapping != nil {
		in, out := &in.NamespaceMapping, &out.NamespaceMapping
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	in.ResourceSelection.DeepCopyInto(&out.ResourceSelection)
	if in.StorageClassMapping != nil {
		in, out := &in.StorageClassMapping, &out.StorageClassMapping
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	in.ConflictPolicy.DeepCopyInto(&out.ConflictPolicy)
	out.Timeout = in.Timeout
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RestoreTaskSpec.
func (in *RestoreTaskSpec) DeepCopy() *RestoreTaskSpec {
	if in == nil {
		return nil
	}
	out := new(RestoreTaskSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RestoreTaskStatus) DeepCopyInto(out *RestoreTaskStatus) {
	*out = *in
	in.CommonStatus.DeepCopyInto(&out.CommonStatus)
	in.Plan.DeepCopyInto(&out.Plan)
	out.Progress = in.Progress
	if in.LastHeartbeatTime != nil {
		in, out := &in.LastHeartbeatTime, &out.LastHeartbeatTime
		*out = (*in).DeepCopy()
	}
	if in.Checkpoints != nil {
		in, out := &in.Checkpoints, &out.Checkpoints
		*out = make([]TaskCheckpoint, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Errors != nil {
		in, out := &in.Errors, &out.Errors
		*out = make([]ErrorDetail, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ResidualResources != nil {
		in, out := &in.ResidualResources, &out.ResidualResources
		*out = make([]ResourceObjectRef, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RestoreTaskStatus.
func (in *RestoreTaskStatus) DeepCopy() *RestoreTaskStatus {
	if in == nil {
		return nil
	}
	out := new(RestoreTaskStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RetentionSpec) DeepCopyInto(out *RetentionSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RetentionSpec.
func (in *RetentionSpec) DeepCopy() *RetentionSpec {
	if in == nil {
		return nil
	}
	out := new(RetentionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RetryPolicy) DeepCopyInto(out *RetryPolicy) {
	*out = *in
	out.Backoff = in.Backoff
	out.MaxBackoff = in.MaxBackoff
	if in.RetryableCodes != nil {
		in, out := &in.RetryableCodes, &out.RetryableCodes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RetryPolicy.
func (in *RetryPolicy) DeepCopy() *RetryPolicy {
	if in == nil {
		return nil
	}
	out := new(RetryPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SFTPAuthSpec) DeepCopyInto(out *SFTPAuthSpec) {
	*out = *in
	out.UsernameRef = in.UsernameRef
	if in.PasswordRef != nil {
		in, out := &in.PasswordRef, &out.PasswordRef
		*out = new(SecretKeyReference)
		**out = **in
	}
	if in.PrivateKeyRef != nil {
		in, out := &in.PrivateKeyRef, &out.PrivateKeyRef
		*out = new(SecretKeyReference)
		**out = **in
	}
	if in.PassphraseRef != nil {
		in, out := &in.PassphraseRef, &out.PassphraseRef
		*out = new(SecretKeyReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SFTPAuthSpec.
func (in *SFTPAuthSpec) DeepCopy() *SFTPAuthSpec {
	if in == nil {
		return nil
	}
	out := new(SFTPAuthSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SFTPRepositorySpec) DeepCopyInto(out *SFTPRepositorySpec) {
	*out = *in
	in.Auth.DeepCopyInto(&out.Auth)
	if in.KnownHostsRef != nil {
		in, out := &in.KnownHostsRef, &out.KnownHostsRef
		*out = new(SecretKeyReference)
		**out = **in
	}
	out.ConnectTimeout = in.ConnectTimeout
	out.OperationTimeout = in.OperationTimeout
	out.KeepAliveInterval = in.KeepAliveInterval
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SFTPRepositorySpec.
func (in *SFTPRepositorySpec) DeepCopy() *SFTPRepositorySpec {
	if in == nil {
		return nil
	}
	out := new(SFTPRepositorySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretKeyReference) DeepCopyInto(out *SecretKeyReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretKeyReference.
func (in *SecretKeyReference) DeepCopy() *SecretKeyReference {
	if in == nil {
		return nil
	}
	out := new(SecretKeyReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecurityConfig) DeepCopyInto(out *SecurityConfig) {
	*out = *in
	if in.AllowedSecretNamespaces != nil {
		in, out := &in.AllowedSecretNamespaces, &out.AllowedSecretNamespaces
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecurityConfig.
func (in *SecurityConfig) DeepCopy() *SecurityConfig {
	if in == nil {
		return nil
	}
	out := new(SecurityConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SelectionPreviewStatus) DeepCopyInto(out *SelectionPreviewStatus) {
	*out = *in
	if in.GeneratedAt != nil {
		in, out := &in.GeneratedAt, &out.GeneratedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SelectionPreviewStatus.
func (in *SelectionPreviewStatus) DeepCopy() *SelectionPreviewStatus {
	if in == nil {
		return nil
	}
	out := new(SelectionPreviewStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SkippedRun) DeepCopyInto(out *SkippedRun) {
	*out = *in
	in.ScheduledAt.DeepCopyInto(&out.ScheduledAt)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SkippedRun.
func (in *SkippedRun) DeepCopy() *SkippedRun {
	if in == nil {
		return nil
	}
	out := new(SkippedRun)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SnapshotResult) DeepCopyInto(out *SnapshotResult) {
	*out = *in
	if in.CreationTime != nil {
		in, out := &in.CreationTime, &out.CreationTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SnapshotResult.
func (in *SnapshotResult) DeepCopy() *SnapshotResult {
	if in == nil {
		return nil
	}
	out := new(SnapshotResult)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TaskCheckpoint) DeepCopyInto(out *TaskCheckpoint) {
	*out = *in
	in.UpdatedAt.DeepCopyInto(&out.UpdatedAt)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TaskCheckpoint.
func (in *TaskCheckpoint) DeepCopy() *TaskCheckpoint {
	if in == nil {
		return nil
	}
	out := new(TaskCheckpoint)
	in.DeepCopyInto(out)
	return out
}
