apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- protection.platform.io_backuppluginconfigs.yaml
- protection.platform.io_backuppolicies.yaml
- protection.platform.io_backuprecords.yaml
- protection.platform.io_backuprepositories.yaml
- protection.platform.io_backupscopes.yaml
- protection.platform.io_backuptasks.yaml
- protection.platform.io_restoretasks.yaml
